train_data_path="/home/oogundep/afsenti_dataset/ha_train.tsv"
eval_data_path="/home/oogundep/afsenti_dataset/ha_test.tsv"
test_data_path="/home/oogundep/afsenti_dataset/ha_test.tsv"
model_name_or_path="castorini/afriteva_small"
tokenizer_name_or_path="castorini/afriteva_small"
max_seq_length="128"
output_dir="/home/oogundep/afsenti_dataset"
learning_rate="3e-4"
train_batch_size="2"
eval_batch_size="2"
num_train_epochs="1"
gradient_accumulation_steps="16"
lang="hausa"
class_labels="positive,negative,neutral"
data_column="tweet"
target_column="label"

export CUDA_AVAILABLE_DEVICES=1
export TOKENIZERS_PARALLELISM=true

python3 classification_scripts/classification_trainer.py --train_data_path=$train_data_path \
    --eval_data_path=$eval_data_path \
    --test_data_path=$test_data_path \
    --model_name_or_path=$model_name_or_path \
    --tokenizer_name_or_path=$tokenizer_name_or_path \
    --output_dir=$output_dir \
    --max_seq_length=$max_seq_length \
    --train_batch_size=$train_batch_size \
    --eval_batch_size=$eval_batch_size \
    --num_train_epochs=$num_train_epochs \
    --gradient_accumulation_steps=$gradient_accumulation_steps \
    --lang=$lang \
    --class_labels=$class_labels \
    --target_column=$target_column \
    --data_column=$data_column \
    --learning_rate="3e-4" \
    --weight_decay="0.0" \
    --adam_epsilon="1e-8" \
    --warmup_steps="0" \
    --n_gpu="1" \
    --fp_16="false" \
    --max_grad_norm="1.0" \
    --opt_level="O1" \
    --seed="42"
